server:
  port: 8989

spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:
        - id: customer-service
          uri: lb://customer-service
          predicates:
            - Path=/customer/**
        - id: book-service
          uri: lb://book-service
          predicates:
            - Path=/book/**
        - id: oauth-server
          uri: lb://OAUTH-SERVER
          predicates:
            - Path=/oauth-server/**
          filters:
            - RewritePath=/oauth-server/(?<path>.*), /$\{path}

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

  instance:
    hostname: localhost
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
